spring:
  application:
    name: big_event
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/big_event
    username: root
    password: 888888

  data:
    redis:
      host: localhost
      port: 6379
      database: 0

mybatis:
  configuration:
    map-underscore-to-camel-case: true # 开启驼峰命名和下划线命名转换
